/**
 * Returns the image URL as-is. Images in portal_capas are already at the
 * correct size (1200×686 WebP) generated by the n8n pipeline, so no
 * transform parameters should be appended.
 */
export function getTransformedImageUrl(
  url: string | null | undefined,
  _width = 600,
  _quality = 80,
): string {
  if (!url) return "";
  return url;
}
