// Página de inscrição do Detox da Primavera 2026. Escrita com createElement (sem JSX).
import { createElement as h, useState, type ReactNode } from "react";
import { Helmet } from "react-helmet-async";
import {
  BookOpen, Briefcase, CalendarDays, Check, ClipboardList, CreditCard, Eye, Flame, HelpCircle, Loader2, MessageCircle,
  Pill, PlayCircle, QrCode, Quote, Sparkles, Sprout, Sun, TrendingUp, Users, UtensilsCrossed, Waves, X,
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import MeuMapaDetox from "@/components/detox/MeuMapaDetox";
import {
  DETOX_INSCRICAO as D, PREMIUM_CARD, RELATOS, RELATO_PREMIUM, RELATO_GRUPO, FRASE_EDSON_2025, RECEITAS, RECEITAS_TITULO, IMAGENS,
} from "@/data/detoxInscricao";

type Metodo = "cartao" | "pix";
type Relato = { texto: string; nome: string; fonte: string };
const ICONES: Record<string, typeof Sun> = { sol: Sun, grupo: Users, aulas: PlayCircle, lista: ClipboardList, cardapio: UtensilsCrossed, duvidas: HelpCircle, premium: Sparkles, lingua: Eye };
const ICONES_PREMIUM: Record<string, typeof Sun> = { akasha: MessageCircle, revisao: TrendingUp, rotina: UtensilsCrossed, lingua: Eye, aulas: BookOpen, conteudo: Sparkles };
const ETAPAS = [
  { icone: Flame, fundo: "bg-gradient-to-br from-[#E8893F] to-[#D0662A]" },
  { icone: Waves, fundo: "bg-gradient-to-br from-[#5D789C] to-[#405979]" },
  { icone: Sprout, fundo: "bg-gradient-to-br from-[#57966E] to-[#39734F]" },
];
const PUBLICOS = [
  { Icone: Sprout, titulo: "Para quem nunca estudou Ayurveda", texto: "Eu ensino do zero, passo a passo, e respondo as dúvidas no grupo." },
  { Icone: Sun, titulo: "Para quem quer mover a vida", texto: "Para quem está com vontade de mover as energias do corpo e da mente nesta primavera." },
  { Icone: Briefcase, titulo: "Para quem trabalha fora", texto: "Dá pra seguir a rotina normalmente e levar a marmita." },
  { Icone: Pill, titulo: "Para quem toma remédio de uso contínuo", texto: "Você continua tomando normalmente. Eu não mexo em medicação." },
];
const TEXTO = "m-0 text-[17px] leading-[1.7] text-[#514B62] md:text-[18px]";
const SUAVE = "m-0 text-[16px] leading-relaxed text-[#655E72] md:text-[17px]";
const olho = (t: string, centro = false) => h("p", { className: `m-0 flex items-center gap-2 text-[15px] font-bold uppercase text-[#A85A1A] ${centro ? "justify-center" : ""}` }, h("img", { src: IMAGENS.sol, alt: "", className: "h-8 w-8", "aria-hidden": true }), t);
const titulo = (t: string) => h("h2", { className: "m-0 font-serif text-[30px] font-bold leading-[1.18] text-[#352F54] text-balance md:text-[38px]" }, t);
const par = (t: string, classe = TEXTO) => h("p", { className: classe }, t);
const secao = (conteudo: ReactNode[], opts: { fundo?: string; largura?: string } = {}) => h("section", { className: `px-4 py-8 md:py-12 ${opts.fundo ?? "bg-gradient-to-b from-[#FDF7F1] to-[#FBE3CC]"}` }, h("div", { className: `mx-auto flex w-full flex-col gap-5 ${opts.largura ?? "max-w-[720px]"}` }, ...conteudo));
const inicial = (nome: string) => nome.trim().charAt(0).toUpperCase() || "A";
const relato = (r: Relato, i = 0, fundo = "bg-white/90") => h("figure", { key: i, className: `m-0 flex h-full flex-col gap-4 rounded-2xl p-5 shadow-[0_14px_35px_-28px_rgba(53,47,84,0.5)] md:p-6 ${fundo}` }, h(Quote, { className: "h-10 w-10 fill-[#FBE3CC] text-[#E07B39]", "aria-hidden": true }), h("blockquote", { className: "m-0 flex-1 font-serif text-[18px] leading-[1.65] text-[#352F54]" }, r.texto), h("figcaption", { className: "flex items-center gap-3" }, h("span", { className: "flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[#E07B39] text-[16px] font-bold text-white" }, inicial(r.nome)), h("span", { className: "flex flex-col text-[14px] leading-snug text-[#655E72]" }, h("strong", { className: "text-[#352F54]" }, r.nome), r.fonte)));
const linhaIcone = (Icone: typeof Sun, t: string, i: number, cor: string) => h("li", { key: i, className: "flex items-start gap-3" }, h(Icone, { className: `mt-1 h-5 w-5 shrink-0 ${cor}`, "aria-hidden": true }), h("span", { className: TEXTO }, t));

const DetoxInscricao = () => {
  const { toast } = useToast();
  const [carregando, setCarregando] = useState(null as Metodo | null);
  const comprar = async (metodo: Metodo) => {
    setCarregando(metodo);
    const { data, error } = await supabase.functions.invoke("create-cartao-curso", { body: { curso_slug: "detox-da-primavera", metodo } });
    if (error || !data) { setCarregando(null); toast({ title: "Não foi possível abrir o pagamento", description: "Tente de novo em instantes.", variant: "destructive" }); return; }
    if (data.ja_matriculado) { toast({ title: "Você já está inscrito no Detox. Abrindo a sua área do curso." }); window.setTimeout(() => { window.location.href = "/cursos/detox-da-primavera/estudar"; }, 700); return; }
    if (data.checkout_url) { window.location.href = data.checkout_url; return; }
    setCarregando(null); toast({ title: "Não foi possível abrir o pagamento", description: "Tente de novo em instantes.", variant: "destructive" });
  };
  const botoes = (escuro = false) => [
    h("button", { key: "cartao", type: "button", onClick: () => void comprar("cartao"), disabled: carregando !== null, className: `flex min-h-[60px] w-full items-center justify-center gap-2.5 rounded-full px-6 text-[16px] font-semibold transition disabled:opacity-70 ${escuro ? "bg-[#F2CB05] text-[#1F1A38] hover:brightness-95" : "bg-[#E07B39] text-white hover:bg-[#D0662A]"}` }, carregando === "cartao" ? h(Loader2, { className: "h-5 w-5 animate-spin" }) : h(CreditCard, { className: "h-5 w-5", "aria-hidden": true }), D.hero.botao_cartao),
    h("button", { key: "pix", type: "button", onClick: () => void comprar("pix"), disabled: carregando !== null, className: `flex min-h-[60px] w-full items-center justify-center gap-2.5 rounded-full px-6 text-[16px] font-semibold transition disabled:opacity-70 ${escuro ? "border border-white/70 text-white hover:bg-white/10" : "border border-[#E07B39] bg-white text-[#A85A1A] hover:bg-[#FFF0E3]"}` }, carregando === "pix" ? h(Loader2, { className: "h-5 w-5 animate-spin" }) : h(QrCode, { className: "h-5 w-5", "aria-hidden": true }), D.hero.botao_pix),
  ];
  const compraCompacta = (key: string) => h("div", { key, className: "mx-auto mt-3 flex w-full max-w-[760px] flex-col gap-3 rounded-3xl bg-white/90 p-5 shadow-[0_18px_45px_-30px_rgba(53,47,84,0.5)] md:p-6" }, h("div", { className: "flex flex-wrap items-end justify-between gap-2" }, h("div", null, h("p", { className: "m-0 text-[14px] font-bold uppercase text-[#A85A1A]" }, "Inscrição no Detox da Primavera"), h("p", { className: "m-0 mt-1 font-serif text-[34px] font-bold text-[#352F54]" }, "R$ 450")), h("p", { className: "m-0 max-w-[330px] text-[15px] text-[#655E72]" }, "Em até 3x de R$ 150 sem juros no cartão, ou R$ 427,50 no Pix.")), h("div", { className: "grid gap-2.5 sm:grid-cols-2" }, ...botoes()));
  const hero = D.hero;

  return h("div", { className: "min-h-screen bg-[#FDF7F1] text-[#514B62]" },
    h(Helmet, null, h("title", null, "Detox da Primavera com Edson Osorio · Portal Ayurveda"), h("meta", { name: "description", content: hero.subtitulo })),
    h("div", { className: "bg-gradient-to-r from-[#1F1A38] to-[#352F54] px-4 py-3 text-center text-[14px] font-bold text-white md:text-[15px]" }, D.faixa),
    h("section", { className: "overflow-hidden bg-gradient-to-b from-[#FBE3CC] to-[#FDF7F1] px-4 pb-8 pt-8 md:pb-12 md:pt-10" },
      h("div", { className: "mx-auto grid max-w-[1080px] items-end gap-6 md:grid-cols-[1.12fr_0.88fr] md:gap-8" },
        h("div", { className: "flex flex-col gap-5" },
          h("div", { className: "flex items-center gap-4" }, h("img", { src: IMAGENS.logo, alt: "Detox da Primavera", className: "h-16 w-auto object-contain md:h-20" }), h("p", { className: "m-0 max-w-[310px] text-[18px] font-bold leading-snug text-[#A85A1A]" }, hero.eyebrow)),
          h("h1", { className: "m-0 font-serif text-[36px] font-bold leading-[1.08] text-[#352F54] text-balance md:text-[52px]" }, hero.titulo),
          par(hero.subtitulo),
          h("div", { className: "mt-1 flex flex-col gap-3 rounded-3xl bg-white/90 p-5 shadow-[0_20px_45px_-30px_rgba(53,47,84,0.5)] md:p-6" }, h("p", { className: "m-0 text-[14px] font-bold uppercase text-[#A85A1A]" }, hero.preco_rotulo), h("div", { className: "flex flex-wrap items-end gap-3" }, h("p", { className: "m-0 font-serif text-[42px] font-bold leading-none text-[#352F54]" }, hero.preco), par(hero.preco_linha, "m-0 pb-1 text-[15px] text-[#655E72]")), h("div", { className: "grid gap-2.5 sm:grid-cols-2" }, ...botoes()), h("p", { className: "m-0 text-[13px] text-[#655E72]" }, hero.nota))),
        h("div", { className: "relative mx-auto flex w-full max-w-[430px] items-end justify-center" },
          h("img", { src: IMAGENS.edsonRecorte, alt: "Edson Osorio", className: "w-full max-w-[370px] object-contain drop-shadow-[0_20px_28px_rgba(53,47,84,0.2)]" }),
          h("div", { className: "absolute bottom-3 right-0 w-[210px] rounded-2xl bg-white/95 p-4 shadow-xl md:right-[-12px]" }, h("p", { className: "m-0 font-serif text-[19px] font-bold text-[#352F54]" }, "Edson Osorio"), ...([[Sun,"15 anos de Ayurveda"],[Users,"Mais de 6.000 alunos formados"],[Sparkles,"6º ano do Detox da Primavera"]] as [typeof Sun, string][]).map(([Icone, texto], i) => h("div", { key: i, className: "mt-2 flex items-center gap-2 text-[12px] font-semibold text-[#514B62]" }, h(Icone, { className: "h-4 w-4 shrink-0 text-[#E07B39]" }), texto)))))),
    h(MeuMapaDetox),

    secao([olho(D.renovar.eyebrow), titulo(D.renovar.titulo), par(D.renovar.texto), h("div", { key: "busca", className: "mt-1 rounded-3xl bg-white/90 p-6 shadow-sm" }, h("p", { className: "m-0 mb-4 font-serif text-[21px] font-bold text-[#352F54]" }, D.renovar.busca_titulo), h("ul", { className: "m-0 flex list-none flex-col gap-3 p-0" }, ...D.renovar.busca.map((t, i) => linhaIcone(Check, t, i, "text-[#3F8A5F]")))), par(D.renovar.ama)]),

    h("section", { className: "bg-gradient-to-b from-[#FBE3CC] to-[#FDF7F1] px-4 py-8 md:py-12" }, h("div", { className: "mx-auto flex max-w-[1080px] flex-col gap-5" }, h("div", { className: "mx-auto flex max-w-[720px] flex-col gap-4 text-center" }, olho(D.processo.eyebrow, true), titulo(D.processo.titulo), par(D.processo.intro)), h("ol", { className: "m-0 mt-2 grid list-none gap-4 p-0 md:grid-cols-3" }, ...D.processo.etapas.map((e, i) => { const est = ETAPAS[i]; return h("li", { key: i, className: `relative flex flex-col gap-3 overflow-hidden rounded-3xl p-6 text-white shadow-lg md:p-7 ${est.fundo}` }, h("span", { className: "absolute -right-3 -top-6 font-serif text-[120px] font-bold leading-none text-white/10" }, String(i + 1)), h(est.icone, { className: "h-8 w-8 text-white" }), h("p", { className: "m-0 text-[13px] font-bold uppercase text-white/90" }, `Etapa ${i + 1} · ${e.nome}`), h("h3", { className: "m-0 font-serif text-[27px] font-bold text-white" }, e.verbo), par(e.texto, "m-0 text-[17px] leading-relaxed text-white")); })), compraCompacta("compra-etapas"), h("p", { className: "m-0 text-center text-[16px] text-[#655E72]" }, D.processo.nota), h("div", { className: "grid gap-3 sm:grid-cols-3" }, ...D.datas.map((d, i) => h("div", { key: i, className: "flex gap-3 rounded-2xl bg-white/80 p-4" }, h(CalendarDays, { className: "h-5 w-5 text-[#E07B39]" }), h("div", null, h("p", { className: "m-0 font-bold text-[#352F54]" }, d.quando), h("p", { className: "m-0 text-[14px] text-[#655E72]" }, d.o_que))))))),

    secao([h("div", { key: "cab", className: "flex flex-col gap-3 text-center" }, olho(RECEITAS_TITULO.eyebrow, true), titulo(RECEITAS_TITULO.titulo), par(RECEITAS_TITULO.texto)), h("div", { key: "grid", className: "grid grid-cols-2 gap-3 md:grid-cols-4" }, ...RECEITAS.map((r, i) => h("figure", { key: i, className: "m-0 overflow-hidden rounded-2xl bg-white shadow-sm" }, h("img", { src: r.img, alt: r.nome, loading: "lazy", className: "aspect-[3/2] w-full object-cover" }), h("figcaption", { className: "px-3 py-3 text-center text-[15px] font-semibold text-[#352F54]" }, r.nome))))], { largura: "max-w-[1080px]" }),

    secao([olho(D.o_que_recebe.eyebrow), titulo(D.o_que_recebe.titulo), h("div", { key: "itens", className: "grid gap-3 sm:grid-cols-2" }, ...D.o_que_recebe.itens.map((x, i) => { const Icone = ICONES[x.icone] ?? Sun; return h("div", { key: i, className: "flex gap-4 rounded-2xl bg-white/90 p-5 shadow-sm" }, h("div", { className: "flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-[#FBE3CC]" }, h(Icone, { className: "h-5 w-5 text-[#E07B39]" })), h("div", null, h("h3", { className: "m-0 text-[17px] font-bold text-[#352F54]" }, x.titulo), h("p", { className: "m-0 mt-1 text-[17px] leading-relaxed text-[#655E72] md:text-[18px]" }, x.texto))); }))], { fundo: "bg-gradient-to-b from-[#FBE3CC] to-[#FDF7F1]", largura: "max-w-[880px]" }),

    h("section", { className: "bg-gradient-to-b from-[#FDF7F1] to-[#FBE3CC] px-4 py-8 md:py-12" }, h("div", { className: "mx-auto flex max-w-[1080px] flex-col gap-6" }, h("div", { className: "rounded-[32px] bg-gradient-to-br from-[#352F54] to-[#1F1A38] p-6 text-white shadow-xl md:p-10" }, h("div", { className: "flex flex-col gap-6" }, h("div", { className: "flex flex-wrap items-center gap-4" }, h("img", { src: PREMIUM_CARD.logo, alt: "Akasha I.A.", className: "h-16 w-16 object-contain" }), h("div", null, h("p", { className: "m-0 text-[15px] font-bold uppercase text-[#F2CB05]" }, PREMIUM_CARD.eyebrow), h("h2", { className: "m-0 mt-1 font-serif text-[30px] font-bold leading-tight text-white md:text-[38px]" }, PREMIUM_CARD.titulo))), h("p", { className: "m-0 max-w-[800px] text-[17px] leading-[1.7] text-white md:text-[18px]" }, PREMIUM_CARD.texto), h("div", { className: "grid gap-3 sm:grid-cols-2 lg:grid-cols-3" }, ...PREMIUM_CARD.itens.map((x, i) => { const Icone = ICONES_PREMIUM[x.icone] ?? Sparkles; return h("div", { key: i, className: "rounded-2xl bg-white/10 p-5" }, h(Icone, { className: "h-6 w-6 text-[#F2CB05]" }), h("p", { className: "m-0 mt-2 text-[17px] font-bold text-white" }, x.titulo), h("p", { className: "m-0 mt-1 text-[16px] leading-relaxed text-white" }, x.texto)); })), h("div", { className: "flex flex-wrap justify-between gap-2 rounded-2xl bg-[#F2CB05] px-5 py-4 text-[#1F1A38]" }, h("p", { className: "m-0 font-bold" }, PREMIUM_CARD.valor_titulo), h("p", { className: "m-0" }, PREMIUM_CARD.valor_texto)))), compraCompacta("compra-premium"), h("div", { className: "grid gap-4 md:grid-cols-2" }, h("figure", { className: "m-0 rounded-3xl bg-white/90 p-6" }, h(Quote, { className: "h-10 w-10 text-[#E07B39]" }), h("blockquote", { className: "m-0 mt-3 font-serif text-[18px] leading-relaxed text-[#352F54]" }, FRASE_EDSON_2025), h("figcaption", { className: "mt-3 text-[14px] text-[#655E72]" }, "Edson Osorio, Detox de 2025")), relato(RELATO_PREMIUM)))),

    secao([olho(D.acompanhamento.eyebrow), titulo(D.acompanhamento.titulo), h("div", { key: "dupla", className: "grid gap-4 md:grid-cols-2" }, h("div", { className: "rounded-3xl bg-white/90 p-6" }, h("h3", { className: "m-0 font-serif text-[22px] font-bold text-[#352F54]" }, "Comigo, durante o Detox"), par("De 5 a 15 de outubro eu faço o meu detox junto com a turma e acompanho você no grupo do WhatsApp, em grupos de até 50 pessoas. Quando alguém pergunta, eu respondo no grupo e todo mundo aprende junto.", "m-0 mt-3 text-[17px] leading-relaxed text-[#514B62] md:text-[18px]")), h("div", { className: "rounded-3xl bg-white/90 p-6" }, h("h3", { className: "m-0 font-serif text-[22px] font-bold text-[#352F54]" }, "Com a Akasha I.A., depois do Detox"), par("Nos 3 meses de Portal Premium, a Akasha, a inteligência artificial do Portal, segue com você: tira as suas dúvidas a qualquer hora, faz a revisão mensal do seu quadro, ajusta a sua rotina e acompanha a leitura da sua língua.", "m-0 mt-3 text-[17px] leading-relaxed text-[#514B62] md:text-[18px]"))), h("p", { key: "cit", className: "m-0 border-l-4 border-[#E07B39] pl-4 font-serif text-[20px] text-[#352F54]" }, `“${D.acompanhamento.citacao}”`), relato(RELATO_GRUPO)], { largura: "max-w-[960px]" }),

    secao([h("div", { key: "cab", className: "flex flex-col gap-3 text-center" }, olho(D.relatos.eyebrow, true), titulo(D.relatos.titulo)), h("div", { key: "rel", className: "grid gap-4 sm:grid-cols-2 lg:grid-cols-3" }, ...RELATOS.map((r, i) => relato(r, i))), compraCompacta("compra-relatos")], { fundo: "bg-gradient-to-b from-[#FBE3CC] to-[#FDF7F1]", largura: "max-w-[1080px]" }),

    secao([h("div", { key: "cab", className: "text-center" }, titulo(D.para_quem.titulo)), h("div", { key: "publicos", className: "grid gap-4 sm:grid-cols-2" }, ...PUBLICOS.map(({ Icone, titulo: nome, texto }, i) => h("article", { key: i, className: "flex gap-4 rounded-3xl bg-white/90 p-6" }, h("div", { className: "flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-[#FBE3CC]" }, h(Icone, { className: "h-6 w-6 text-[#E07B39]" })), h("div", null, h("h3", { className: "m-0 text-[18px] font-bold text-[#352F54]" }, nome), h("p", { className: "m-0 mt-2 text-[17px] leading-relaxed text-[#514B62] md:text-[18px]" }, texto))))), h("div", { key: "nao", className: "flex flex-col gap-3 rounded-2xl bg-[#FFF0E3] p-4 sm:flex-row sm:items-center" }, h("p", { className: "m-0 shrink-0 font-bold text-[#A85A1A]" }, D.para_quem.titulo_nao), h("div", { className: "grid flex-1 gap-2 sm:grid-cols-2" }, ...D.para_quem.nao.map((t, i) => h("span", { key: i, className: "flex items-center gap-2 text-[16px] text-[#514B62]" }, h(X, { className: "h-4 w-4 text-[#D0662A]" }), t))))], { largura: "max-w-[960px]" }),

    secao([h("div", { key: "cab", className: "text-center" }, titulo(D.pagamento.titulo)), h("div", { key: "cards", className: "grid gap-3 sm:grid-cols-2" }, [[CreditCard,D.pagamento.cartao_titulo,D.pagamento.cartao_texto],[QrCode,D.pagamento.pix_titulo,D.pagamento.pix_texto]].map(([Icone, nome, texto], i) => h("div", { key: i, className: "flex gap-4 rounded-2xl bg-white/90 p-5" }, h(Icone as typeof CreditCard, { className: "h-6 w-6 shrink-0 text-[#E07B39]" }), h("div", null, h("p", { className: "m-0 text-[17px] font-bold text-[#352F54]" }, nome as string), par(texto as string, SUAVE))))), h("div", { key: "bot", className: "mx-auto grid w-full max-w-[620px] gap-2.5 sm:grid-cols-2" }, ...botoes()), h("p", { key: "nota", className: "m-0 text-center text-[14px] text-[#655E72]" }, D.pagamento.nota)], { fundo: "bg-gradient-to-b from-[#FBE3CC] to-[#FDF7F1]" }),

    secao([h("div", { key: "cab", className: "flex flex-col items-center gap-3 text-center" }, olho("Tire suas dúvidas", true), titulo("Perguntas frequentes")), h("div", { key: "faq", className: "grid items-start gap-3 md:grid-cols-2" }, ...D.faq.map((x, i) => h("details", { key: i, className: "group rounded-2xl bg-white/90 p-5" }, h("summary", { className: "flex cursor-pointer list-none items-center justify-between gap-4 text-[17px] font-bold text-[#352F54]" }, x.pergunta, h("span", { className: "flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-[#E07B39] text-[22px] text-white transition-transform group-open:rotate-45" }, "+")), h("p", { className: "m-0 mt-3 text-[17px] leading-relaxed text-[#514B62] md:text-[18px]" }, x.resposta))))], { largura: "max-w-[960px]" }),

    secao([h("div", { key: "prof", className: "grid items-center gap-6 md:grid-cols-[0.8fr_1.2fr] md:gap-10" }, h("img", { src: IMAGENS.edsonFoto, alt: "Edson Osorio", className: "mx-auto w-full max-w-[390px] rounded-3xl object-cover shadow-lg" }), h("div", { className: "flex flex-col gap-4" }, h("div", null, h("p", { className: "m-0 font-serif text-[30px] font-bold text-[#352F54]" }, "Edson Osorio"), h("p", { className: "m-0 mt-1 text-[16px] text-[#A85A1A]" }, D.professor.papel)), ...D.professor.bio.map((t, i) => par(t, `${TEXTO} ${i === 0 ? "font-semibold" : ""}`)), h("p", { className: "m-0 border-l-4 border-[#E07B39] pl-4 font-serif text-[20px] text-[#352F54]" }, `“${D.professor.citacao}”`)))], { fundo: "bg-gradient-to-b from-[#FBE3CC] to-[#FDF7F1]", largura: "max-w-[980px]" }),

    h("section", { className: "bg-gradient-to-br from-[#352F54] to-[#1F1A38] px-4 py-10 md:py-14" }, h("div", { className: "mx-auto flex max-w-[680px] flex-col items-center gap-4 text-center" }, h("img", { src: IMAGENS.logo, alt: "Detox da Primavera", className: "h-[120px] w-auto object-contain" }), h("div", null, h("p", { className: "m-0 font-serif text-[24px] font-bold text-white" }, "Detox da Primavera"), h("p", { className: "m-0 mt-1 text-[17px] text-white" }, "com Edson Osorio")), h("h2", { className: "m-0 font-serif text-[30px] font-bold leading-tight text-white md:text-[38px]" }, D.fechamento.titulo), h("p", { className: "m-0 text-[17px] leading-[1.7] text-white md:text-[18px]" }, D.fechamento.texto), h("p", { className: "m-0 text-[16px] font-semibold text-[#FBE3CC]" }, D.fechamento.preco_linha), h("div", { className: "mt-2 grid w-full max-w-[540px] gap-2.5" }, ...botoes(true)))
  ));
};
export default DetoxInscricao;
