GRANT USAGE ON SCHEMA loja TO anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA loja TO anon, authenticated;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA loja TO anon, authenticated;

ALTER DEFAULT PRIVILEGES IN SCHEMA loja
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO anon, authenticated;

ALTER DEFAULT PRIVILEGES IN SCHEMA loja
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO anon, authenticated;