-- Initial v1.0 seed of dosha test content
INSERT INTO public.dosha_test_questions (part, "group", sort_order, text, options, tag_label) VALUES
('part1', NULL, 0, 'Sua maneira de se expressar é mais:', '[{"label":"Rápida, com gesticulação (movimento) ou, às vezes, um pouco rouca.","scores":{"v":2}},{"label":"Clara, intensa e, por vezes, crítica ou argumentativa.","scores":{"p":2}},{"label":"Lenta, suave ou reservada (prefiro ouvir).","scores":{"k":2}}]'::jsonb, NULL),
('part1', NULL, 1, 'Como você lida com mudanças inesperadas em sua rotina?', '[{"label":"Fico ansioso(a), inseguro(a), com medo ou dúvida.","scores":{"v":2,"agni_irregular":1}},{"label":"Fico estressado(a) e imediatamente busco a melhor solução e ordem.","scores":{"p":2}},{"label":"Fico resistente e prefiro manter o que é familiar e confortável.","scores":{"k":2}}]'::jsonb, NULL),
('part1', NULL, 2, 'Qual emoção você sente com mais frequência ou intensidade quando está sob estresse?', '[{"label":"Ansiedade, nervosismo ou medo de que algo ruim aconteça.","scores":{"v":2,"agni_irregular":1}},{"label":"Irritação, raiva ou impaciência com a lentidão dos outros.","scores":{"p":2,"agni_forte":1}},{"label":"Melancolia, apatia ou busca por conforto (comer, dormir).","scores":{"k":2,"agni_fraco":2}},{"label":"Oscilo entre ansiedade e frustração/raiva.","scores":{"v":1,"p":1}}]'::jsonb, NULL),
('part1', NULL, 3, 'Como está o fluxo de suas ideias e sua capacidade de concentração?', '[{"label":"Tenho muitas ideias e sou criativo(a), mas a mente está dispersa e me esqueço dos detalhes.","scores":{"v":2,"agni_irregular":1}},{"label":"Minha mente é focada, analítica e busca o discernimento rápido para resolver problemas.","scores":{"p":2,"agni_forte":1}},{"label":"Mente estável e calma, mas demoro para iniciar novos projetos (letargia mental).","scores":{"k":2}},{"label":"Mente agitada e analítica ao mesmo tempo (ansiedade com necessidade de controle).","scores":{"v":1,"p":1}},{"label":"Mente lenta para iniciar e dispersa para finalizar.","scores":{"v":1,"k":1}}]'::jsonb, NULL),
('part2', NULL, 0, 'Meu apetite é geralmente:', '[{"label":"Irregular, às vezes como, às vezes me esqueço de comer.","scores":{"v":2,"agni_irregular":2}},{"label":"Forte e intenso (fico irritado se não como na hora certa).","scores":{"p":2,"agni_forte":2}},{"label":"Fraco ou lento para aparecer, tenho peso no estômago.","scores":{"k":2,"agni_fraco":2}}]'::jsonb, NULL),
('part2', NULL, 1, 'O que você sente mais frequentemente após as refeições?', '[{"label":"Gases ou estufamento (espaço vazio e movimento no trato digestivo).","scores":{"v":2,"agni_irregular":2}},{"label":"Acidez ou queimação (fogo/calor).","scores":{"p":2,"agni_forte":2}},{"label":"Sonolência e peso na barriga.","scores":{"k":2,"v":1,"agni_fraco":2}},{"label":"Gases com queimação ou acidez.","scores":{"v":2,"p":2,"agni_irregular":1,"agni_forte":1}},{"label":"Peso e letargia com estufamento e gases.","scores":{"v":2,"k":2,"agni_fraco":1,"agni_irregular":1}}]'::jsonb, NULL),
('part2', NULL, 2, 'Sua capacidade de transformar o que come é:', '[{"label":"Irregular (digestão inconstante, ora rápida, ora lenta demais).","scores":{"v":1,"agni_irregular":1}},{"label":"Intensa (o alimento é queimado rápido e tenho muita fome logo depois).","scores":{"p":1,"agni_forte":1}},{"label":"Lenta e fraca (demora para sentir fome novamente).","scores":{"v":2,"k":2,"agni_fraco":1}},{"label":"Intensa e lenta (acidez e peso estomacal).","scores":{"p":2,"k":2}}]'::jsonb, NULL),
('part3', NULL, 0, 'Minha urina é:', '[{"label":"Escassa, posso segurar, faço pouco xixi.","scores":{"v":2,"agni_irregular":1}},{"label":"Amarelada escura ou quente, constante e abundante.","scores":{"p":2,"agni_forte":1}},{"label":"Com odor, posso ir pouco mas é volumosa.","scores":{"k":2,"agni_fraco":1}}]'::jsonb, NULL),
('part3', NULL, 1, 'Meu suor e odor corporal é:', '[{"label":"Quase não suo, e minha pele é seca.","scores":{"v":2}},{"label":"Suor excessivo, quente ou com odor forte/ácido.","scores":{"p":2}},{"label":"Suor moderado, pele oleosa ou com tendência a retenção de líquido.","scores":{"k":1}},{"label":"Pouco suor e pele quente e seca.","scores":{"v":1,"p":1}},{"label":"Suor quente, amarelado, oleoso e úmido.","scores":{"p":2,"k":2}}]'::jsonb, NULL),
('part3', NULL, 2, 'Minhas evacuações são tipicamente:', '[{"label":"Constipadas, secas, difíceis de eliminar.","scores":{"v":3}},{"label":"Soltas, com cheiro forte e tendência à diarreia.","scores":{"p":3}},{"label":"Grandes, pesadas, pastosas ou com muco.","scores":{"k":3}}]'::jsonb, NULL),
('part4', NULL, 0, 'Meu corpo tende a ser:', '[{"label":"Magro ou leve, assimétrico, com dificuldade em ganhar peso.","scores":{"v":2}},{"label":"Mediano, atlético, simétrico, ganha tônus com facilidade.","scores":{"p":3}},{"label":"Robusto, arredondado com facilidade em ganhar peso e dificuldade em perder.","scores":{"k":3}}]'::jsonb, NULL),
('part4', NULL, 1, 'Sinto minhas articulações e ossos com mais:', '[{"label":"Estalos, rigidez ou dor que muda de lugar, às vezes some.","scores":{"v":2}},{"label":"Inflamação articular, tendinite, dores quentes pulsantes.","scores":{"p":1}},{"label":"Peso, inchaço ou edemas, retendo líquido.","scores":{"k":1}}]'::jsonb, NULL),
('part4', NULL, 2, 'Minha pele é mais:', '[{"label":"Seca, fria e áspera (falta de umidade/nutrição).","scores":{"v":2,"agni_irregular":1}},{"label":"Sensível, com vermelhidão ou manchas e pintas.","scores":{"p":2,"agni_forte":1}},{"label":"Oleosa, fria e densa (untuosidade).","scores":{"k":2,"agni_fraco":1}}]'::jsonb, NULL),
('part4', NULL, 3, 'Saúde Íntima / Ciclo Menstrual:', '[{"label":"Ciclo irregular, cólicas fortes, pouco fluxo.","scores":{"v":2}},{"label":"Fluxo intenso, sangue bem vermelho, queimação ou TPM com irritação.","scores":{"p":2}},{"label":"Fluxo denso, retenção de líquido, cólica pesada e constante.","scores":{"k":2}},{"label":"Não menstruo / Menopausa / Sou homem.","scores":{}}]'::jsonb, NULL),
('part5', NULL, 0, 'Minha energia física e vigor são:', '[{"label":"Oscilantes, com picos e quedas, sentindo pouca vitalidade.","scores":{"v":2,"agni_irregular":1}},{"label":"Intensos, mas me sinto esgotado(a) se não descansar (alto metabolismo).","scores":{"p":2,"agni_forte":1}},{"label":"Estáveis, com grande resistência e paciência.","scores":{"k":2}}]'::jsonb, NULL),
('part5', NULL, 1, 'Em relação à minha saúde geral, eu:', '[{"label":"Adoeço facilmente, sinto que minha imunidade é frágil.","scores":{"v":2,"agni_irregular":1}},{"label":"Sou propenso(a) a infecções ou inflamações (ites).","scores":{"p":2,"agni_forte":1}},{"label":"Sou propenso(a) a muco, congestionamento, inchaço e edemas.","scores":{"k":2,"agni_fraco":1}}]'::jsonb, NULL),
('part6', NULL, 0, 'Meu sono costuma ser mais:', '[{"label":"Leve, com insônia ou dificuldade em manter o sono. Acordo facilmente.","scores":{"v":2,"agni_irregular":1}},{"label":"Penso muito pra dormir mas quando apago consigo aprofundar, posso acordar irritado.","scores":{"p":2,"agni_forte":1}},{"label":"Durmo com facilidade, sinto dificuldade em acordar ou tenho letargia.","scores":{"k":2,"agni_fraco":1}}]'::jsonb, NULL),
('part6', NULL, 1, 'Meu ritmo e horários diários (comer, dormir) são:', '[{"label":"Irregulares e inconstantes (não tenho horários fixos).","scores":{"v":2,"agni_irregular":1}},{"label":"Intensos, acelerados e cheios de compromissos.","scores":{"p":2,"agni_forte":1}},{"label":"Lentos, estáveis e busco o conforto.","scores":{"k":2,"agni_fraco":1}}]'::jsonb, NULL),
('part6', NULL, 2, 'Meu estilo de trabalho ou hobbies é:', '[{"label":"Criativo, envolvo-me em multitarefas e adoro viajar.","scores":{"v":1}},{"label":"Competitivo, focado em resultados e liderança.","scores":{"p":1}},{"label":"Estável, prefiro ambientes acolhedores e familiares.","scores":{"k":2}},{"label":"Multitarefas e competitivo.","scores":{"v":2,"p":2}}]'::jsonb, NULL),
('part6', NULL, 3, 'Quando você tem um tempo livre para lazer, que tipo de energia você prefere gastar?', '[{"label":"Gosto de usar minha imaginação e criatividade. Prefiro atividades leves, artísticas ou mentais.","scores":{"v":2}},{"label":"Gosto de atividades que exigem foco, disputa e desafio, gosto de testar meus limites.","scores":{"p":2}},{"label":"Gosto mais de ficar em casa e relaxar, optar por ler ou assistir algo, passear levemente.","scores":{"k":2}}]'::jsonb, NULL),
('part7', NULL, 0, 'O clima que mais me incomoda ou agrava minha saúde é:', '[{"label":"Frio, vento e tempo seco.","scores":{"v":1,"k":1}},{"label":"Calor, sol forte ou tempo quente em geral.","scores":{"p":1,"k":1}},{"label":"Tempo úmido, chuvoso e frio.","scores":{"v":1,"k":1}}]'::jsonb, NULL),
('part7', NULL, 1, 'Quando preciso tomar decisões, eu as tomo de forma:', '[{"label":"Confusa ou indecisa, mudando de ideia facilmente.","scores":{"v":2}},{"label":"Penetrante, com clareza e convicção (discernimento abundante).","scores":{"p":2}},{"label":"Lenta, com resistência ou por falta de clareza.","scores":{"k":2}}]'::jsonb, NULL),
('part7', NULL, 2, 'Meu corpo se sente mais frequentemente:', '[{"label":"Frio ou com as extremidades frias (mãos e pés).","scores":{"v":2}},{"label":"Quente ou com tendência a calor nas extremidades.","scores":{"p":2}},{"label":"Frio, mas com sensação de densidade ou peso.","scores":{"k":2}}]'::jsonb, NULL),
('part7', NULL, 3, 'Em termos de constituição física, eu sou mais:', '[{"label":"Alto(a), magro(a), com ossos proeminentes.","scores":{"v":2}},{"label":"De altura média, atlético(a) ou com densidade muscular.","scores":{"p":2}},{"label":"Robusto(a), com ganho de peso, com estrutura larga.","scores":{"k":3}}]'::jsonb, NULL),
('agravamentos', 'vata', 0, NULL, '[{"label":"Ansiedade","scores":{"v":2}}]'::jsonb, 'Ansiedade'),
('agravamentos', 'vata', 1, NULL, '[{"label":"Insônia","scores":{"v":2}}]'::jsonb, 'Insônia'),
('agravamentos', 'vata', 2, NULL, '[{"label":"Confusão mental","scores":{"v":2}}]'::jsonb, 'Confusão mental'),
('agravamentos', 'vata', 3, NULL, '[{"label":"Zumbido no ouvido","scores":{"v":2}}]'::jsonb, 'Zumbido no ouvido'),
('agravamentos', 'vata', 4, NULL, '[{"label":"Estufamento abdominal","scores":{"v":2}}]'::jsonb, 'Estufamento abdominal'),
('agravamentos', 'vata', 5, NULL, '[{"label":"Frio nas extremidades","scores":{"v":2}}]'::jsonb, 'Frio nas extremidades'),
('agravamentos', 'vata', 6, NULL, '[{"label":"Anemia","scores":{"v":2}}]'::jsonb, 'Anemia'),
('agravamentos', 'vata', 7, NULL, '[{"label":"Ressecamento de pele","scores":{"v":2}}]'::jsonb, 'Ressecamento de pele'),
('agravamentos', 'vata', 8, NULL, '[{"label":"Constipação","scores":{"v":2}}]'::jsonb, 'Constipação'),
('agravamentos', 'vata', 9, NULL, '[{"label":"Gases","scores":{"v":2}}]'::jsonb, 'Gases'),
('agravamentos', 'vata', 10, NULL, '[{"label":"Dor nas articulações","scores":{"v":2}}]'::jsonb, 'Dor nas articulações'),
('agravamentos', 'vata', 11, NULL, '[{"label":"Arritmia","scores":{"v":2}}]'::jsonb, 'Arritmia'),
('agravamentos', 'vata', 12, NULL, '[{"label":"Indigestão","scores":{"v":2}}]'::jsonb, 'Indigestão'),
('agravamentos', 'vata', 13, NULL, '[{"label":"Problemas ósseos","scores":{"v":2}}]'::jsonb, 'Problemas ósseos'),
('agravamentos', 'pitta', 0, NULL, '[{"label":"Estresse","scores":{"p":2}}]'::jsonb, 'Estresse'),
('agravamentos', 'pitta', 1, NULL, '[{"label":"Nervosismo","scores":{"p":2}}]'::jsonb, 'Nervosismo'),
('agravamentos', 'pitta', 2, NULL, '[{"label":"Rosácea/melasma","scores":{"p":2}}]'::jsonb, 'Rosácea/melasma'),
('agravamentos', 'pitta', 3, NULL, '[{"label":"Refluxo","scores":{"p":2}}]'::jsonb, 'Refluxo'),
('agravamentos', 'pitta', 4, NULL, '[{"label":"Burnout","scores":{"p":2}}]'::jsonb, 'Burnout'),
('agravamentos', 'pitta', 5, NULL, '[{"label":"Inflamações","scores":{"p":2}}]'::jsonb, 'Inflamações'),
('agravamentos', 'pitta', 6, NULL, '[{"label":"Azia","scores":{"p":2}}]'::jsonb, 'Azia'),
('agravamentos', 'pitta', 7, NULL, '[{"label":"Dejetos mal formados","scores":{"p":2}}]'::jsonb, 'Dejetos mal formados'),
('agravamentos', 'pitta', 8, NULL, '[{"label":"Fome excessiva","scores":{"p":2}}]'::jsonb, 'Fome excessiva'),
('agravamentos', 'pitta', 9, NULL, '[{"label":"Aftas","scores":{"p":2}}]'::jsonb, 'Aftas'),
('agravamentos', 'pitta', 10, NULL, '[{"label":"Calor nas extremidades","scores":{"p":2}}]'::jsonb, 'Calor nas extremidades'),
('agravamentos', 'pitta', 11, NULL, '[{"label":"Problemas de visão","scores":{"p":2}}]'::jsonb, 'Problemas de visão'),
('agravamentos', 'pitta', 12, NULL, '[{"label":"Dermatite","scores":{"p":2}}]'::jsonb, 'Dermatite'),
('agravamentos', 'pitta', 13, NULL, '[{"label":"Infecções recorrentes","scores":{"p":2}}]'::jsonb, 'Infecções recorrentes'),
('agravamentos', 'kapha', 0, NULL, '[{"label":"Letargia","scores":{"k":2}}]'::jsonb, 'Letargia'),
('agravamentos', 'kapha', 1, NULL, '[{"label":"Sensação de peso","scores":{"k":2}}]'::jsonb, 'Sensação de peso'),
('agravamentos', 'kapha', 2, NULL, '[{"label":"Obesidade","scores":{"k":2}}]'::jsonb, 'Obesidade'),
('agravamentos', 'kapha', 3, NULL, '[{"label":"Asma","scores":{"k":2}}]'::jsonb, 'Asma'),
('agravamentos', 'kapha', 4, NULL, '[{"label":"Tosse mucosa","scores":{"k":2}}]'::jsonb, 'Tosse mucosa'),
('agravamentos', 'kapha', 5, NULL, '[{"label":"Salivação excessiva","scores":{"k":2}}]'::jsonb, 'Salivação excessiva'),
('agravamentos', 'kapha', 6, NULL, '[{"label":"Sono excessivo","scores":{"k":2}}]'::jsonb, 'Sono excessivo'),
('agravamentos', 'kapha', 7, NULL, '[{"label":"Respiração pesada","scores":{"k":2}}]'::jsonb, 'Respiração pesada'),
('agravamentos', 'kapha', 8, NULL, '[{"label":"Flacidez","scores":{"k":2}}]'::jsonb, 'Flacidez'),
('agravamentos', 'kapha', 9, NULL, '[{"label":"Diabetes","scores":{"k":2}}]'::jsonb, 'Diabetes'),
('agravamentos', 'kapha', 10, NULL, '[{"label":"Fungos","scores":{"k":2}}]'::jsonb, 'Fungos'),
('agravamentos', 'kapha', 11, NULL, '[{"label":"Edema","scores":{"k":2}}]'::jsonb, 'Edema'),
('agravamentos', 'kapha', 12, NULL, '[{"label":"Digestão lenta","scores":{"k":2}}]'::jsonb, 'Digestão lenta'),
('agravamentos', 'kapha', 13, NULL, '[{"label":"Suor pegajoso","scores":{"k":2}}]'::jsonb, 'Suor pegajoso'),
('foods', 'vata', 0, NULL, '[{"label":"Saladas","scores":{"v":1}}]'::jsonb, 'Saladas'),
('foods', 'vata', 1, NULL, '[{"label":"Frutas","scores":{"v":1}}]'::jsonb, 'Frutas'),
('foods', 'vata', 2, NULL, '[{"label":"Chás","scores":{"v":1}}]'::jsonb, 'Chás'),
('foods', 'vata', 3, NULL, '[{"label":"Integrais","scores":{"v":1}}]'::jsonb, 'Integrais'),
('foods', 'vata', 4, NULL, '[{"label":"Torradas","scores":{"v":1}}]'::jsonb, 'Torradas'),
('foods', 'vata', 5, NULL, '[{"label":"Germinados","scores":{"v":1}}]'::jsonb, 'Germinados'),
('foods', 'pitta', 0, NULL, '[{"label":"Conservas","scores":{"p":1}}]'::jsonb, 'Conservas'),
('foods', 'pitta', 1, NULL, '[{"label":"Molhos","scores":{"p":1}}]'::jsonb, 'Molhos'),
('foods', 'pitta', 2, NULL, '[{"label":"Bebidas Alcoólicas","scores":{"p":1}}]'::jsonb, 'Bebidas Alcoólicas'),
('foods', 'pitta', 3, NULL, '[{"label":"Pimentas","scores":{"p":1}}]'::jsonb, 'Pimentas'),
('foods', 'pitta', 4, NULL, '[{"label":"Especiarias","scores":{"p":1}}]'::jsonb, 'Especiarias'),
('foods', 'pitta', 5, NULL, '[{"label":"Fermentados","scores":{"p":1}}]'::jsonb, 'Fermentados'),
('foods', 'kapha', 0, NULL, '[{"label":"Beliscos/Petiscos","scores":{"k":1}}]'::jsonb, 'Beliscos/Petiscos'),
('foods', 'kapha', 1, NULL, '[{"label":"Doces","scores":{"k":1}}]'::jsonb, 'Doces'),
('foods', 'kapha', 2, NULL, '[{"label":"Massas","scores":{"k":1}}]'::jsonb, 'Massas'),
('foods', 'kapha', 3, NULL, '[{"label":"Queijos","scores":{"k":1}}]'::jsonb, 'Queijos'),
('foods', 'kapha', 4, NULL, '[{"label":"Sementes","scores":{"k":1}}]'::jsonb, 'Sementes'),
('foods', 'kapha', 5, NULL, '[{"label":"Frituras/Salgados","scores":{"k":1}}]'::jsonb, 'Frituras/Salgados');

-- Snapshot v1.0 into versions table
INSERT INTO public.dosha_test_versions (label, snapshot)
VALUES (
  'v1.0 — estado original',
  (SELECT jsonb_agg(to_jsonb(q) ORDER BY part, "group" NULLS FIRST, sort_order)
     FROM public.dosha_test_questions q)
);