// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Singleton absoluto: garante que existe apenas UMA instância do cliente
// Supabase no browser, mesmo com hot reload do Vite ou múltiplos imports.
// Múltiplas instâncias com o mesmo storageKey disputam o refresh do token e
// causam loops de token_revoked → SIGNED_OUT (logout aleatório).
const GLOBAL_KEY = '__portalayurveda_supabase_client__';

type GlobalWithSupabase = typeof globalThis & {
  [GLOBAL_KEY]?: SupabaseClient<Database>;
};

const globalRef = globalThis as GlobalWithSupabase;

export const supabase: SupabaseClient<Database> =
  globalRef[GLOBAL_KEY] ??
  createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
      storageKey: 'sb-portalayurveda-auth',
    },
  });

if (typeof window !== 'undefined') {
  globalRef[GLOBAL_KEY] = supabase;
}
