// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Singleton absoluto: garante que existe apenas UMA instância do cliente
// Supabase no browser, mesmo com hot reload do Vite ou múltiplos imports.
// Múltiplas instâncias com o mesmo storageKey disputam o refresh do token e
// causam loops de token_revoked → SIGNED_OUT (logout aleatório).
const GLOBAL_KEY = '__portalayurveda_supabase_client__';

type GlobalWithSupabase = typeof globalThis & {
  [GLOBAL_KEY]?: SupabaseClient<Database>;
};

const globalRef = globalThis as GlobalWithSupabase;

export const supabase: SupabaseClient<Database> =
  globalRef[GLOBAL_KEY] ??
  createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
      storageKey: 'sb-portalayurveda-auth',
    },
  });

// Reescreve URLs públicas de Storage para o domínio público de imagens
// (api.portalayurveda.com), mantendo o endpoint original do Supabase para
// auth, DB e chamadas autenticadas de Storage.
const LEGACY_STORAGE_HOST = SUPABASE_URL?.replace(/\/$/, '') ?? '';
const PUBLIC_IMAGE_HOST = 'https://api.portalayurveda.com';

if (!globalRef[GLOBAL_KEY] && LEGACY_STORAGE_HOST) {
  const originalFrom = supabase.storage.from.bind(supabase.storage);
  supabase.storage.from = ((bucketId: string) => {
    const bucket = originalFrom(bucketId);
    const originalGetPublicUrl = bucket.getPublicUrl.bind(bucket);
    bucket.getPublicUrl = ((path: string, options?: Parameters<typeof originalGetPublicUrl>[1]) => {
      const result = originalGetPublicUrl(path, options);
      if (result?.data?.publicUrl?.startsWith(LEGACY_STORAGE_HOST)) {
        result.data.publicUrl =
          PUBLIC_IMAGE_HOST + result.data.publicUrl.slice(LEGACY_STORAGE_HOST.length);
      }
      return result;
    }) as typeof bucket.getPublicUrl;
    return bucket;
  }) as typeof supabase.storage.from;
}

if (typeof window !== 'undefined') {
  globalRef[GLOBAL_KEY] = supabase;
}
