// Dedicated Supabase client for the "premium" schema (clinical analysis &
// treatment plan generated by the AI pipeline). Uses the same pattern as
// loja-client.ts because the typed default client is locked to "public".

import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string;

export const premiumSupabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  db: { schema: "premium" as never },
  auth: {
    persistSession: false,
    autoRefreshToken: false,
  },
});

// ---------- Types ----------

export interface ObjetivoTratamento {
  id: string;
  user_email: string;
  vata_atual: number | null;
  vata_status: string | null;
  vata_meta: number | null;
  pitta_atual: number | null;
  pitta_status: string | null;
  pitta_meta: number | null;
  kapha_atual: number | null;
  kapha_status: string | null;
  kapha_meta: number | null;
  agni_tipo: string | null;
  agni_nivel_atual: number | null;
  agni_nivel_meta: number | null;
  o_que_e: string | null;
  causas: string[] | null;
  objetivos: string[] | null;
  primario_slug: string | null;
  primario_tipo: string | null; // 'produto' | 'kit'
  upgrade_kit_slug: string | null;
  suplementar_slug: string | null;
  frase_clinica: string | null;
  status: string | null;
  data_inicio: string | null;
  data_fim: string | null;
  narrativa_clinica: {
    bloco_1_situacao?: string;
    bloco_2_causas?: string;
    bloco_3_caminhos?: string;
  } | null;
  deficit_doshas: string[] | null;
}
